# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Install cron
RUN apt-get update && apt-get install -y cron \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file into the container at /app
COPY requirements.txt ./

# Install any needed packages specified in requirements.txt
# Ensure APScheduler is not in requirements.txt anymore
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY . .

# Copy entrypoint script and give execution rights
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Create a crontab file and set permissions
COPY crontab /etc/cron.d/crontab
RUN chmod 0644 /etc/cron.d/crontab \
    && crontab /etc/cron.d/crontab

# Set the entrypoint script to run when the container starts
ENTRYPOINT ["/entrypoint.sh"]
